// <auto-generated />
using System;
using DreamJob.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DreamJob.Server.Migrations
{
    [DbContext(typeof(DreamJobContext))]
    partial class DreamJobContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DreamJob.Server.Models.DreamJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DreamJobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 16, 18, 37, 59, 541, DateTimeKind.Utc).AddTicks(973),
                            JobDetails = "We are seeking a talented Senior Full Stack Developer to join our innovative team. \n\n**About the Role:**\nIn this position, you will be responsible for designing, developing, and maintaining both front-end and back-end components of our web applications. You'll work closely with cross-functional teams to deliver high-quality software solutions.\n\n**What You'll Do:**\n• Design and implement scalable web applications\n• Collaborate with designers and product managers\n• Write clean, maintainable code\n• Mentor junior developers\n• Participate in code reviews and technical discussions\n\n**What We Offer:**\n• Competitive salary and benefits\n• Remote-first work environment\n• Professional development opportunities\n• Flexible working hours\n• Modern tech stack",
                            LastModifiedDate = new DateTime(2026, 2, 16, 18, 37, 59, 541, DateTimeKind.Utc).AddTicks(1185),
                            Title = "Senior Full Stack Developer"
                        });
                });

            modelBuilder.Entity("DreamJob.Server.Models.JobSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DreamJobId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DreamJobId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DreamJobId = 1,
                            IsCustom = false,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            DreamJobId = 1,
                            IsCustom = false,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 3,
                            DreamJobId = 1,
                            IsCustom = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            DreamJobId = 1,
                            IsCustom = false,
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 5,
                            DreamJobId = 1,
                            IsCustom = false,
                            Name = "REST APIs"
                        },
                        new
                        {
                            Id = 6,
                            DreamJobId = 1,
                            IsCustom = false,
                            Name = "Git"
                        });
                });

            modelBuilder.Entity("DreamJob.Server.Models.JobSkill", b =>
                {
                    b.HasOne("DreamJob.Server.Models.DreamJob", "DreamJob")
                        .WithMany("Skills")
                        .HasForeignKey("DreamJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DreamJob");
                });

            modelBuilder.Entity("DreamJob.Server.Models.DreamJob", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
